name: Sync with Remote Repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout local repository
      uses: actions/checkout@v2

    - name: Sync with remote repository
      run: |
        git remote add upstream https://github.com/movie-web/simple-proxy
        git fetch upstream
        git checkout dev
        git merge upstream/dev --no-edit
        git push origin main
