name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Scheduled to run every 30 minutes. Adjust as needed.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/movie-web/simple-proxy
          git fetch upstream

      - name: Sync Fork
        run: |
          git checkout dev # Replace with your default branch if it's not 'main'
          git merge upstream/dev # Replace with your default branch if it's not 'main'
          git push
